CATALOG_NAME = "workspace_us"
SCHEMA_NAME = "default"
TABLE_NAME = "pubmed"
VS_ENDPOINT_NAME = "pubned_vs_endpoint"
VS_INDEX = "pubmed_index"
VS_INDEX_TABLE_FULLNAME = f"{CATALOG_NAME}.{SCHEMA_NAME}.{VS_INDEX}"